# Copyright 2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
  radius:
    image: tpdock/freeradius:latest
    restart: on-failure
    environment:
      - RADIUS_LISTEN_IP=*
      - USERS_FILE=/etc/raddb/users
      - RADIUS_CLIENTS=SECRET@0.0.0.0/0
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    volumes:
      - /home/vagrant/radius/clients.conf:/etc/raddb/clients.conf
      - /home/vagrant/radius/users:/etc/raddb/users

  dhcpd:
    image: sirferdek/isc-dhcp-server:latest
    restart: on-failure
    ports:
      - 67:67/udp
    volumes:
      - /home/vagrant/dhcpd/var/:/var/lib/dhcp/:rw
      - /home/vagrant/dhcpd/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    command:
      - -d
